# Generated by Django 4.0.5 on 2022-07-27 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='champion',
            old_name='skin',
            new_name='clan',
        ),
    ]
